-- =====================================================
-- INSTRUCCIONES PARA CONFIGURAR SUPABASE STORAGE
-- =====================================================
-- 
-- Este script NO se ejecuta automáticamente. Sigue estos pasos
-- en el Dashboard de Supabase para habilitar la carga de archivos:
--
-- 1. Ve a tu proyecto en https://supabase.com/dashboard
-- 2. En el menú lateral, haz clic en "Storage"
-- 3. Haz clic en "New bucket"
-- 4. Configura el bucket:
--    - Name: archivos-casos
--    - Public bucket: YES (marcado)
--    - File size limit: 50MB
--    - Allowed MIME types (opcional): image/*, application/pdf, video/*, audio/*
-- 5. Haz clic en "Save"
--
-- 6. Configura las políticas RLS del bucket:
--    - Ve a "Policies" en el bucket creado
--    - Crea las siguientes políticas:
--
--    POLÍTICA 1 - Lectura pública:
--    - Policy name: "Public read access"
--    - Allowed operation: SELECT
--    - Target roles: anon, authenticated
--    - USING expression: true
--
--    POLÍTICA 2 - Subida para usuarios autenticados:
--    - Policy name: "Authenticated uploads"
--    - Allowed operation: INSERT
--    - Target roles: authenticated
--    - WITH CHECK expression: true
--
--    POLÍTICA 3 - Eliminación para usuarios autenticados:
--    - Policy name: "Authenticated deletes"
--    - Allowed operation: DELETE
--    - Target roles: authenticated
--    - USING expression: true
--
-- =====================================================
-- Una vez configurado, los usuarios podrán subir archivos
-- desde el formulario de recursos en la aplicación.
-- =====================================================

SELECT 'Por favor configura el bucket de Storage siguiendo las instrucciones en este archivo' as instrucciones;
