SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."casos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "id_interno" "text",
    "numero_expediente" "text",
    "estado" "text" DEFAULT 'Iniciado'::"text" NOT NULL,
    "id_victima" bigint,
    "id_hecho" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."casos" OWNER TO "postgres";


COMMENT ON TABLE "public"."casos" IS 'Tabla principal para almacenar los casos del observatorio';



COMMENT ON COLUMN "public"."casos"."id" IS 'Identificador único del caso (UUID)';



COMMENT ON COLUMN "public"."casos"."id_interno" IS 'Identificador interno del caso (opcional)';



COMMENT ON COLUMN "public"."casos"."numero_expediente" IS 'Número de expediente judicial (opcional)';



COMMENT ON COLUMN "public"."casos"."estado" IS 'Estado actual del caso';



COMMENT ON COLUMN "public"."casos"."id_victima" IS 'Referencia a la víctima del caso (bigint)';



COMMENT ON COLUMN "public"."casos"."id_hecho" IS 'Referencia al hecho del caso (bigint)';



COMMENT ON COLUMN "public"."casos"."created_at" IS 'Fecha y hora de creación del registro';



COMMENT ON COLUMN "public"."casos"."updated_at" IS 'Fecha y hora de última actualización del registro';



CREATE TABLE IF NOT EXISTS "public"."consultas_derivadas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "fecha_contacto" "date",
    "nombre_persona_contacto" "text",
    "motivo_consulta" "text",
    "organizacion_derivada" "text",
    "observaciones" "text"
);


ALTER TABLE "public"."consultas_derivadas" OWNER TO "postgres";


COMMENT ON TABLE "public"."consultas_derivadas" IS 'Registra consultas generales que son derivadas a otras organizaciones.';



ALTER TABLE "public"."consultas_derivadas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."consultas_derivadas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."hechos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_victima" bigint,
    "fecha_hecho" "date",
    "lugar_hecho" "text",
    "edad_victima_al_hecho" integer,
    "contexto_hecho" "text",
    "resumen_hecho" "text",
    "nro_causa_judicial" "text",
    "radicacion_causa" "text",
    "circunscripcion_judicial" "text",
    "abogado_querellante" "text"
);


ALTER TABLE "public"."hechos" OWNER TO "postgres";


COMMENT ON TABLE "public"."hechos" IS 'Contiene los detalles de los sucesos o casos.';



ALTER TABLE "public"."hechos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hechos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."hechos_imputados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_hecho" bigint NOT NULL,
    "id_imputado" bigint NOT NULL,
    "vinculo_con_victima" "text",
    "situacion_procesal" "text",
    "lugar_detencion" "text",
    "tiene_defensa_particular" boolean,
    "abogado_defensor" "text",
    "instancia_procesal" "text",
    "calificacion_legal" "text",
    "tiene_antecedentes_penales" boolean,
    "descripcion_antecedentes" "text",
    "categoria_menor" "text",
    "medidas_de_seguridad" "text",
    "sentencia_declaratoria_culpabilidad" boolean,
    "pena" "text"
);


ALTER TABLE "public"."hechos_imputados" OWNER TO "postgres";


COMMENT ON TABLE "public"."hechos_imputados" IS 'Conecta los hechos con los imputados y detalla la situación procesal.';



ALTER TABLE "public"."hechos_imputados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hechos_imputados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."imputados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "nombre_apellido" "text" NOT NULL,
    "alias" "text",
    "nacionalidad" "text",
    "fecha_nacimiento" "date"
);


ALTER TABLE "public"."imputados" OWNER TO "postgres";


COMMENT ON TABLE "public"."imputados" IS 'Almacena la información de las personas imputadas.';



ALTER TABLE "public"."imputados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."imputados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."recursos_multimedia" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_hecho" bigint NOT NULL,
    "tipo_recurso" "text",
    "url_recurso" "text" NOT NULL,
    "descripcion" "text"
);


ALTER TABLE "public"."recursos_multimedia" OWNER TO "postgres";


COMMENT ON TABLE "public"."recursos_multimedia" IS 'Almacena enlaces a archivos multimedia (ej. Supabase Storage) relacionados con un hecho.';



ALTER TABLE "public"."recursos_multimedia" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."recursos_multimedia_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."seguimiento_usina" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "id_hecho" bigint NOT NULL,
    "fecha_ingreso_usina" "date",
    "miembro_usina_asignado" "text",
    "familiar_contacto_principal" "text",
    "vinculo_familiar" "text",
    "telefono_contacto" "text",
    "redes_sociales_para_difusion" "text",
    "acompanamiento_brindado" "text",
    "observaciones_generales" "text"
);


ALTER TABLE "public"."seguimiento_usina" OWNER TO "postgres";


COMMENT ON TABLE "public"."seguimiento_usina" IS 'Registra el seguimiento interno de cada caso.';



ALTER TABLE "public"."seguimiento_usina" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seguimiento_usina_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."victimas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "nombre_apellido" "text" NOT NULL,
    "fecha_nacimiento" "date",
    "nacionalidad" "text",
    "estudios_cursados" "text",
    "profesion" "text",
    "colectivo_pertenencia" "text"
);


ALTER TABLE "public"."victimas" OWNER TO "postgres";


COMMENT ON TABLE "public"."victimas" IS 'Almacena la información personal de las víctimas.';



ALTER TABLE "public"."victimas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."victimas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."casos"
    ADD CONSTRAINT "casos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."consultas_derivadas"
    ADD CONSTRAINT "consultas_derivadas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hechos_imputados"
    ADD CONSTRAINT "hechos_imputados_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hechos"
    ADD CONSTRAINT "hechos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."imputados"
    ADD CONSTRAINT "imputados_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recursos_multimedia"
    ADD CONSTRAINT "recursos_multimedia_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."seguimiento_usina"
    ADD CONSTRAINT "seguimiento_usina_id_hecho_key" UNIQUE ("id_hecho");



ALTER TABLE ONLY "public"."seguimiento_usina"
    ADD CONSTRAINT "seguimiento_usina_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."victimas"
    ADD CONSTRAINT "victimas_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_casos_estado" ON "public"."casos" USING "btree" ("estado");



CREATE INDEX "idx_casos_id_hecho" ON "public"."casos" USING "btree" ("id_hecho");



CREATE INDEX "idx_casos_id_interno" ON "public"."casos" USING "btree" ("id_interno");



CREATE INDEX "idx_casos_id_victima" ON "public"."casos" USING "btree" ("id_victima");



CREATE INDEX "idx_casos_numero_expediente" ON "public"."casos" USING "btree" ("numero_expediente");



CREATE OR REPLACE TRIGGER "update_casos_updated_at" BEFORE UPDATE ON "public"."casos" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."casos"
    ADD CONSTRAINT "casos_id_hecho_fkey" FOREIGN KEY ("id_hecho") REFERENCES "public"."hechos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."casos"
    ADD CONSTRAINT "casos_id_victima_fkey" FOREIGN KEY ("id_victima") REFERENCES "public"."victimas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hechos"
    ADD CONSTRAINT "hechos_id_victima_fkey" FOREIGN KEY ("id_victima") REFERENCES "public"."victimas"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."hechos_imputados"
    ADD CONSTRAINT "hechos_imputados_id_hecho_fkey" FOREIGN KEY ("id_hecho") REFERENCES "public"."hechos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hechos_imputados"
    ADD CONSTRAINT "hechos_imputados_id_imputado_fkey" FOREIGN KEY ("id_imputado") REFERENCES "public"."imputados"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recursos_multimedia"
    ADD CONSTRAINT "recursos_multimedia_id_hecho_fkey" FOREIGN KEY ("id_hecho") REFERENCES "public"."hechos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."seguimiento_usina"
    ADD CONSTRAINT "seguimiento_usina_id_hecho_fkey" FOREIGN KEY ("id_hecho") REFERENCES "public"."hechos"("id") ON DELETE CASCADE;



CREATE POLICY "Enable delete access for everyone" ON "public"."casos" FOR DELETE USING (true);



CREATE POLICY "Enable insert access for everyone" ON "public"."casos" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for everyone" ON "public"."casos" FOR SELECT USING (true);



CREATE POLICY "Enable update access for everyone" ON "public"."casos" FOR UPDATE USING (true);



ALTER TABLE "public"."casos" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."casos" TO "anon";
GRANT ALL ON TABLE "public"."casos" TO "authenticated";
GRANT ALL ON TABLE "public"."casos" TO "service_role";



GRANT ALL ON TABLE "public"."consultas_derivadas" TO "anon";
GRANT ALL ON TABLE "public"."consultas_derivadas" TO "authenticated";
GRANT ALL ON TABLE "public"."consultas_derivadas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."consultas_derivadas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."consultas_derivadas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."consultas_derivadas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."hechos" TO "anon";
GRANT ALL ON TABLE "public"."hechos" TO "authenticated";
GRANT ALL ON TABLE "public"."hechos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."hechos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."hechos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."hechos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."hechos_imputados" TO "anon";
GRANT ALL ON TABLE "public"."hechos_imputados" TO "authenticated";
GRANT ALL ON TABLE "public"."hechos_imputados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."hechos_imputados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."hechos_imputados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."hechos_imputados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."imputados" TO "anon";
GRANT ALL ON TABLE "public"."imputados" TO "authenticated";
GRANT ALL ON TABLE "public"."imputados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."imputados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."imputados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."imputados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."recursos_multimedia" TO "anon";
GRANT ALL ON TABLE "public"."recursos_multimedia" TO "authenticated";
GRANT ALL ON TABLE "public"."recursos_multimedia" TO "service_role";



GRANT ALL ON SEQUENCE "public"."recursos_multimedia_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."recursos_multimedia_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."recursos_multimedia_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."seguimiento_usina" TO "anon";
GRANT ALL ON TABLE "public"."seguimiento_usina" TO "authenticated";
GRANT ALL ON TABLE "public"."seguimiento_usina" TO "service_role";



GRANT ALL ON SEQUENCE "public"."seguimiento_usina_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."seguimiento_usina_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."seguimiento_usina_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."victimas" TO "anon";
GRANT ALL ON TABLE "public"."victimas" TO "authenticated";
GRANT ALL ON TABLE "public"."victimas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."victimas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."victimas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."victimas_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
